import { UnifiedTask, Course, Competition, Committee } from '@/types';

export const INITIAL_COURSES: Course[] = [
  {
    id: 'sbd',
    course_name: 'Sistem Basis Data',
    day_of_week: 3,
    start_time: '09:00',
    end_time: '11:00',
    room_location: 'Lab Komputer 2',
    lecturer: 'Dr. Bayu Pratama',
    credits_sks: 3,
    type: 'Wajib Prodi',
    time: 'Rabu 09:00 - 11:00',
    hasPendingTask: true,
  },
  {
    id: 'mpti',
    course_name: 'Manajemen Proyek TI',
    day_of_week: 2,
    start_time: '07:00',
    end_time: '09:00',
    room_location: 'Ruang C204',
    lecturer: 'Bu Rina',
    credits_sks: 3,
    type: 'Wajib Prodi',
    time: 'Selasa 07:00 - 09:00',
    hasPendingTask: true,
  },
  {
    id: 'algo',
    course_name: 'Algoritma & Struktur Data',
    day_of_week: 1,
    start_time: '09:00',
    end_time: '11:00',
    room_location: 'Ruang A301',
    lecturer: 'Pak Hendra',
    credits_sks: 4,
    type: 'Wajib Prodi',
    time: 'Senin 09:00 - 11:00',
    hasPendingTask: true,
  },
  {
    id: 'jarkom',
    course_name: 'Jaringan Komputer',
    day_of_week: 4,
    start_time: '11:00',
    end_time: '13:00',
    room_location: 'Ruang A105',
    lecturer: 'Pak Budi',
    credits_sks: 3,
    type: 'Wajib Prodi',
    time: 'Kamis 11:00 - 13:00',
    hasPendingTask: true,
  },
  {
    id: 'ai',
    course_name: 'Kecerdasan Buatan',
    day_of_week: 5,
    start_time: '09:00',
    end_time: '11:00',
    room_location: 'Ruang A301',
    lecturer: 'Bu Sarah',
    credits_sks: 3,
    type: 'Pilihan',
    time: 'Jumat 09:00 - 11:00',
    hasPendingTask: false,
  },
  {
    id: 'bing',
    course_name: 'Bahasa Inggris Teknik',
    day_of_week: 1,
    start_time: '13:00',
    end_time: '15:00',
    room_location: 'Ruang B102',
    lecturer: 'Pak Ahmad',
    credits_sks: 2,
    type: 'Wajib Universitas',
    time: 'Senin 13:00 - 15:00',
    hasPendingTask: false,
  },
];

export const INITIAL_COMPETITIONS: Competition[] = [
  {
    id: 'comp-1',
    name: 'UI/UX Hackathon 2026',
    category: 'Hackathon',
    status: 'PROSES_PENGERJAAN',
    level: 'Nasional',
    description: 'Redesain aplikasi transportasi umum perkotaan untuk penumpang lansia.',
    submission_deadline: '2026-09-19T23:59:00',
    deadlineDisplay: 'Submit 3 hari lagi',
    progressPct: 57,
    progressDone: 4,
    progressTotal: 7,
    team_members: 'AR, BK, DL',
  },
  {
    id: 'comp-2',
    name: 'Business Case Competition',
    category: 'Business Case',
    status: 'MENDAFTAR',
    level: 'Nasional',
    description: 'Strategi ekspansi retail lokal ke pasar digital dan ekosistem omnichannel.',
    submission_deadline: '2026-09-28T23:59:00',
    deadlineDisplay: 'Daftar 12 hari lagi',
    progressPct: 0,
    progressDone: 0,
    progressTotal: 2,
    team_members: 'AR, SM',
  },
  {
    id: 'comp-3',
    name: 'Lomba Karya Tulis Ilmiah',
    category: 'LKTI',
    status: 'SUDAH_SUBMIT',
    level: 'Nasional',
    description: 'Pemanfaatan sensor IoT untuk monitoring kualitas air sungai kota.',
    submission_deadline: '2026-09-10T23:59:00',
    deadlineDisplay: 'Menunggu pengumuman',
    progressPct: 100,
    progressDone: 5,
    progressTotal: 5,
    team_members: 'AR, FP',
  },
  {
    id: 'comp-4',
    name: 'Datathon Nasional',
    category: 'Datathon',
    status: 'HASIL_KELUAR',
    level: 'Nasional',
    description: 'Model prediksi curah hujan wilayah Bali berbasis spatial temporal transformer.',
    submission_deadline: '2026-08-30T23:59:00',
    deadlineDisplay: 'Juara 3',
    progressPct: 100,
    progressDone: 6,
    progressTotal: 6,
    team_members: 'AR, KH, RT',
    achievement: 'Juara 3',
  },
];

export const INITIAL_COMMITTEES: Committee[] = [
  {
    id: 'comm-1',
    organization_event_name: 'Panitia OSPEK 2026',
    role_division: 'Sie Acara',
    role: 'Koordinator Acara',
    status: 'Sedang Berjalan',
    start_date: '2026-08-01',
    end_date: '2026-09-30',
    periodDisplay: '1 Agu – 30 Sep 2026',
    progressPct: 65,
    remainingDays: '12 hari tersisa',
    meetingTitle: 'Rapat Koordinasi Rundown',
    meetingTime: 'Kamis, 18 Sep · 16:00 WIB',
    meetingLocation: 'via Zoom Meeting',
    recurring: true,
    jobDescDone: 5,
    jobDescTotal: 7,
    jobDescPct: 71,
    notes: 'Bertanggung jawab atas jalannya rangkaian acara pembukaan dan pengenalan kampus.',
  },
  {
    id: 'comm-2',
    organization_event_name: 'Seminar Nasional Teknologi',
    role_division: 'Koordinator Publikasi',
    role: 'Staff Publikasi',
    status: 'Fase Awal',
    start_date: '2026-09-15',
    end_date: '2026-11-20',
    periodDisplay: '15 Sep – 20 Nov 2026',
    progressPct: 12,
    remainingDays: 'Baru dimulai',
    meetingTitle: 'Kickoff Rapat Perdana',
    meetingTime: 'Sabtu, 20 Sep · 09:00 WIB',
    meetingLocation: 'Ruang Himpunan Lt. 2',
    recurring: true,
    jobDescDone: 1,
    jobDescTotal: 6,
    jobDescPct: 17,
    notes: 'Mengelola publikasi media sosial dan relasi media eksternal.',
  },
  {
    id: 'comm-3',
    organization_event_name: 'Dies Natalis Fakultas',
    role_division: 'Divisi Dokumentasi',
    role: 'Anggota Aktif',
    status: 'Arsip Selesai',
    start_date: '2026-06-01',
    end_date: '2026-07-31',
    periodDisplay: '1 Jun – 31 Jul 2026',
    progressPct: 100,
    remainingDays: 'Selesai',
    meetingTitle: 'Evaluasi Akhir LPJ',
    meetingTime: 'Agenda Rapat Selesai',
    meetingLocation: 'Sekretariat BEM',
    recurring: false,
    jobDescDone: 8,
    jobDescTotal: 8,
    jobDescPct: 100,
    notes: 'Seluruh arsip dokumentasi foto dan video telah diserahkan.',
  },
];

export const INITIAL_TASKS: UnifiedTask[] = [
  // Kuliah (11 tasks)
  {
    id: 't-1',
    title: 'Kumpulkan Laporan Praktikum Modul 4',
    parent_title: 'Sistem Basis Data',
    category: 'KULIAH',
    deadline: '2026-09-18T23:59:00',
    deadlineDisplay: '18 Sep',
    status: 'SEDANG_DIKERJAKAN',
  },
  {
    id: 't-6',
    title: 'Tugas 2: Class Diagram & Use Case',
    parent_title: 'Algoritma & Struktur Data',
    category: 'KULIAH',
    deadline: '2026-09-23T23:59:00',
    deadlineDisplay: '23 Sep',
    status: 'BELUM_MULAI',
  },
  {
    id: 't-7',
    title: 'Konfigurasi Subnetting Packet Tracer',
    parent_title: 'Jaringan Komputer',
    category: 'KULIAH',
    deadline: '2026-09-25T23:59:00',
    deadlineDisplay: '25 Sep',
    status: 'BELUM_MULAI',
  },
  {
    id: 't-9',
    title: 'Tugas Stored Procedure & Trigger Bab 5',
    parent_title: 'Sistem Basis Data',
    category: 'KULIAH',
    deadline: '2026-09-27T23:59:00',
    deadlineDisplay: '27 Sep',
    status: 'BELUM_MULAI',
  },
  {
    id: 't-11',
    title: 'Praktikum AI: Pencarian Jalur A*',
    parent_title: 'Kecerdasan Buatan',
    category: 'KULIAH',
    deadline: '2026-09-29T23:59:00',
    deadlineDisplay: '29 Sep',
    status: 'SEDANG_DIKERJAKAN',
  },
  {
    id: 't-12',
    title: 'Essay Analisis Jurnal Bahasa Inggris',
    parent_title: 'Bahasa Inggris Teknik',
    category: 'KULIAH',
    deadline: '2026-10-02T23:59:00',
    deadlineDisplay: '2 Okt',
    status: 'BELUM_MULAI',
  },
  {
    id: 't-13',
    title: 'Quiz 1 Struktur Pohon Biner',
    parent_title: 'Algoritma & Struktur Data',
    category: 'KULIAH',
    deadline: '2026-09-12T10:00:00',
    deadlineDisplay: '12 Sep',
    status: 'SELESAI',
  },
  {
    id: 't-14',
    title: 'Laporan Praktikum Modul 3 Subnetting',
    parent_title: 'Jaringan Komputer',
    category: 'KULIAH',
    deadline: '2026-09-11T23:59:00',
    deadlineDisplay: '11 Sep',
    status: 'SELESAI',
  },
  {
    id: 't-15',
    title: 'Presentasi Bisnis Bahasa Inggris',
    parent_title: 'Bahasa Inggris Teknik',
    category: 'KULIAH',
    deadline: '2026-09-08T15:00:00',
    deadlineDisplay: '8 Sep',
    status: 'SELESAI',
  },
  {
    id: 't-16',
    title: 'Tugas Resume Normalisasi Database',
    parent_title: 'Sistem Basis Data',
    category: 'KULIAH',
    deadline: '2026-09-05T23:59:00',
    deadlineDisplay: '5 Sep',
    status: 'SELESAI',
  },
  {
    id: 't-17',
    title: 'Makalah Manajemen Risiko TI',
    parent_title: 'Manajemen Proyek TI',
    category: 'KULIAH',
    deadline: '2026-10-05T23:59:00',
    deadlineDisplay: '5 Okt',
    status: 'SEDANG_DIKERJAKAN',
  },

  // Lomba (6 tasks)
  {
    id: 't-2',
    title: 'Revisi Prototype Figma Interaktif',
    parent_title: 'UI/UX Hackathon 2026',
    category: 'LOMBA',
    deadline: '2026-09-19T23:59:00',
    deadlineDisplay: '19 Sep',
    status: 'SEDANG_DIKERJAKAN',
  },
  {
    id: 't-4',
    title: 'Pengujian Usability Testing Tahap 1',
    parent_title: 'UI/UX Hackathon 2026',
    category: 'LOMBA',
    deadline: '2026-09-21T15:00:00',
    deadlineDisplay: '21 Sep',
    status: 'BELUM_MULAI',
  },
  {
    id: 't-10',
    title: 'Submit Berkas Pendaftaran Lomba',
    parent_title: 'Business Case Competition',
    category: 'LOMBA',
    deadline: '2026-09-28T23:59:00',
    deadlineDisplay: '28 Sep',
    status: 'BELUM_MULAI',
  },
  {
    id: 't-18',
    title: 'Riset Target Pasar & Analisis Kompetitor',
    parent_title: 'Business Case Competition',
    category: 'LOMBA',
    deadline: '2026-09-24T18:00:00',
    deadlineDisplay: '24 Sep',
    status: 'SEDANG_DIKERJAKAN',
  },
  {
    id: 't-19',
    title: 'Finalisasi Naskah Karya Tulis Ilmiah',
    parent_title: 'Lomba Karya Tulis Ilmiah',
    category: 'LOMBA',
    deadline: '2026-09-09T23:59:00',
    deadlineDisplay: '9 Sep',
    status: 'SELESAI',
  },
  {
    id: 't-20',
    title: 'Submission Model Transformer & Notebook',
    parent_title: 'Datathon Nasional',
    category: 'LOMBA',
    deadline: '2026-08-29T23:59:00',
    deadlineDisplay: '29 Agu',
    status: 'SELESAI',
  },

  // Kepanitiaan (7 tasks)
  {
    id: 't-3',
    title: 'Desain Poster Rundown Acara',
    parent_title: 'Panitia OSPEK 2026',
    category: 'KEPANITIAAN',
    deadline: '2026-09-20T18:00:00',
    deadlineDisplay: '20 Sep',
    status: 'BELUM_MULAI',
  },
  {
    id: 't-5',
    title: 'Proposal Pengajuan Sponsorship Brand A',
    parent_title: 'Seminar Nasional Teknologi',
    category: 'KEPANITIAAN',
    deadline: '2026-09-22T12:00:00',
    deadlineDisplay: '22 Sep',
    status: 'SEDANG_DIKERJAKAN',
  },
  {
    id: 't-8',
    title: 'Briefing Pengisi Acara & MC',
    parent_title: 'Panitia OSPEK 2026',
    category: 'KEPANITIAAN',
    deadline: '2026-09-26T14:00:00',
    deadlineDisplay: '26 Sep',
    status: 'SELESAI',
  },
  {
    id: 't-21',
    title: 'Koordinasi Teknis Perlengkapan & Sound',
    parent_title: 'Panitia OSPEK 2026',
    category: 'KEPANITIAAN',
    deadline: '2026-09-25T16:00:00',
    deadlineDisplay: '25 Sep',
    status: 'BELUM_MULAI',
  },
  {
    id: 't-22',
    title: 'Pembuatan Feed Publikasi Instagram',
    parent_title: 'Seminar Nasional Teknologi',
    category: 'KEPANITIAAN',
    deadline: '2026-09-21T17:00:00',
    deadlineDisplay: '21 Sep',
    status: 'SEDANG_DIKERJAKAN',
  },
  {
    id: 't-23',
    title: 'Notulensi Rapat Pleno 1',
    parent_title: 'Seminar Nasional Teknologi',
    category: 'KEPANITIAAN',
    deadline: '2026-09-27T19:00:00',
    deadlineDisplay: '27 Sep',
    status: 'BELUM_MULAI',
  },
  {
    id: 't-24',
    title: 'Pengarsipan Foto & Dokumentasi LPJ',
    parent_title: 'Dies Natalis Fakultas',
    category: 'KEPANITIAAN',
    deadline: '2026-07-30T17:00:00',
    deadlineDisplay: '30 Jul',
    status: 'SELESAI',
  },
];
